trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '18.x'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(NODE_VERSION)
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build React App'

- task: AzureStaticWebApp@0
  displayName: 'Deploy to Azure Static Web App'
  inputs:
    app_location: "/"
    output_location: "dist"
    azure_static_web_apps_api_token: "3badbf154b20ee4f1d5adef0857465546ec7606d1e637d1ecbb502d110fd75c601-e5884373-f0d1-4ab6-bdb9-77939e4054140001509059cff300"